server:
  port: 8000
int_server:
  port: 8001

redis:
  url: "redis:6379"
  password: ""

postgres:
  url: "postgres:5432"
  user: "user_local"
  password: "user"
  database: "user"

cache_enabled: true

logger:
  level: debug